[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BRUVpy"
authors = [{name = "Nick Mortimer", email = "nick.mortimer@csiro.au"}]
dynamic = ["version", "description"]
